[font]
normal = ["CaskaydiaMono Nerd Font"]
size = 16

[font.features]
"CaskaydiaCove Nerd Font" = ['+ss01', '+ss02', '+ss03', '+ss04', '+ss05', '+ss06', '+ss20', '+zero', '+onum', '+calt']
"CaskaydiaMono Nerd Font" = ['+ss01', '+ss03', '+ss04', '+ss05', '+ss06', '+ss20', '+zero', '+onum', '+calt']

