[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vicmd_symbol = "[<](bold green)"

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[hostname]
disabled = false
ssh_symbol = "ssh:"
style = "red"

[username]
disabled = false
style_user = "bold blue"

[cmake]
symbol = "cmake "

[dart]
symbol = "dart "

[dotnet]
symbol = ".NET "

[directory]
read_only = " ro"

[docker_context]
symbol = "docker "

[git_branch]
symbol = "git "

[golang]
symbol = "go "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[nodejs]
symbol = "node "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[package]
disabled = true
symbol = "pkg "

[perl]
symbol = "perl "

[python]
symbol = "py "

[rust]
symbol = "rust "

[sudo]
symbol = "sudo "

