[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vicmd_symbol = "[<](bold green)"

[hostname]
disabled = false
ssh_symbol = " "

[username]
disabled = false
style_user = "bold blue"

[cmake]
symbol = "喝 "

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[dotnet]
format = "via [$symbol($version )]($style)"

[elixir]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
disabled = true
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[zig]
symbol = " "